=== tuanflute275/BTL_XML_1/btl.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="EmployeeId" type="xs:positiveInteger"></xs:element>

    <xs:element name="FirstName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="2"></xs:minLength>
                <xs:maxLength value="50"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="LastName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="2"></xs:minLength>
                <xs:maxLength value="50"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Email"> 
        <xs:simpleType>
            <xs:restriction base="xs:string"> 
                <xs:pattern value="[^\s@]+@[^\s]+\.[^\s]{2,3}"/> 
            </xs:restriction> 
        </xs:simpleType>
    </xs:element>

    <xs:element name="PhoneNumber">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{10}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Date" type="xs:date"></xs:element>

    <xs:element name="JobId">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"></xs:minInclusive>
                <xs:maxInclusive value="15"></xs:maxInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Salary">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="900"></xs:minInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:simpleType name="formatManagerID">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\s\w\n]*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="ManagerId">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="formatManagerID">
                    <xs:attribute name="note" use="optional"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="EmployeeId"></xs:element>
                <xs:element ref="FirstName"></xs:element>
                <xs:element ref="LastName"></xs:element>
                <xs:element ref="Email"></xs:element>
                <xs:element ref="PhoneNumber"></xs:element>
                <xs:element ref="Date"></xs:element>
                <xs:element ref="JobId"></xs:element>
                <xs:element ref="Salary"></xs:element>
                <xs:element ref="ManagerId"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Employee" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueId">
            <xs:selector xpath="Employee/EmployeeId"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:unique>
    </xs:element>

</xs:schema>

=== tuanflute275/BTL_XML_1/btl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet href="yc1.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc2.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc3.xsl" type="text/xsl"?>? -->
<!-- <?xml-stylesheet href="yc4.xsl" type="text/xsl"?> -->
<?xml-stylesheet href="yc5.xsl" type="text/xsl"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="btl.xsd" >
    <Employee>
        <EmployeeId>101</EmployeeId>
        <FirstName>Tô Ngọc</FirstName>
        <LastName>Anh</LastName>
        <Email>ngocanh11@gmail.com</Email>
        <PhoneNumber>0966242899</PhoneNumber>
        <Date>2019-01-15</Date>
        <JobId>11</JobId>
        <Salary>2500</Salary>
        <ManagerId>108</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>102</EmployeeId>
        <FirstName>Phạm Khải</FirstName>
        <LastName>Hoàn</LastName>
        <Email>hoan15402@gmail.com</Email>
        <PhoneNumber>0967322322</PhoneNumber>
        <Date>2021-03-25</Date>
        <JobId>3</JobId>
        <Salary>2250</Salary>
        <ManagerId>102</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>103</EmployeeId>
        <FirstName>Dương Long</FirstName>
        <LastName>Đình</LastName>
        <Email>longdinhduong24@gmail.com</Email>
        <PhoneNumber>0386345189</PhoneNumber>
        <Date>2022-01-01</Date>
        <JobId>4</JobId>
        <Salary>1750</Salary>
        <ManagerId>101</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>104</EmployeeId>
        <FirstName>Hoàng Lan</FirstName>
        <LastName>Hương</LastName>
        <Email>lanhuong231@gmail.com</Email>
        <PhoneNumber>0988678999</PhoneNumber>
        <Date>2021-06-01</Date>
        <JobId>2</JobId>
        <Salary>2400</Salary>
        <ManagerId>109</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>105</EmployeeId>
        <FirstName>Trần Minh</FirstName>
        <LastName>Chiến</LastName>
        <Email>chientran44@gmail.com</Email>
        <PhoneNumber>0963253647</PhoneNumber>
        <Date>2017-08-01</Date>
        <JobId>1</JobId>
        <Salary>2550</Salary>
        <ManagerId>105</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>106</EmployeeId>
        <FirstName>Phan Chiến</FirstName>
        <LastName>Thắng</LastName>
        <Email>thang210799@gmail.com</Email>
        <PhoneNumber>0826468231</PhoneNumber>
        <Date>2021-07-18</Date>
        <JobId>2</JobId>
        <Salary>1800</Salary>
        <ManagerId>108</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>107</EmployeeId>
        <FirstName>Nguyễn Yến</FirstName>
        <LastName>Nhi</LastName>
        <Email>yennhi201@gmail.com</Email>
        <PhoneNumber>0966214953</PhoneNumber>
        <Date>2019-04-01</Date>
        <JobId>15</JobId>
        <Salary>2600</Salary>
        <ManagerId>108</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>108</EmployeeId>
        <FirstName>Lê Quang</FirstName>
        <LastName>Minh</LastName>
        <Email>lqminh98@gmail.com</Email>
        <PhoneNumber>0962624952</PhoneNumber>
        <Date>2022-01-07</Date>
        <JobId>2</JobId>
        <Salary>1650</Salary>
        <ManagerId>107</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>109</EmployeeId>
        <FirstName>Ngô Tiến</FirstName>
        <LastName>Đạt</LastName>
        <Email>ngotiendat3103@gmail.com</Email>
        <PhoneNumber>0382624769</PhoneNumber>
        <Date>2016-02-11</Date>
        <JobId>7</JobId>
        <Salary>2950</Salary>
        <ManagerId>108</ManagerId>
    </Employee>
    <Employee>
        <EmployeeId>110</EmployeeId>
        <FirstName>Đỗ Đức</FirstName>
        <LastName>Long</LastName>
        <Email>long14102@gmail.com</Email>
        <PhoneNumber>0388698589</PhoneNumber>
        <Date>2019-07-07</Date>
        <JobId>6</JobId>
        <Salary>2050</Salary>
        <ManagerId>104</ManagerId>
    </Employee>
</Employees>
